# Runs on pull requests

name: Deploy Previews

on:
  pull_request:
    branches:
      - dev
      - main
      - ghaction-vercel

jobs:
  lint:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.DOCS_ORG_ID}}
          vercel-project-id: ${{ secrets.DOCS_PROJECT_ID}}
          working-directory: ./
